alias ll="ls -alh"
alias tfswitch='tfswitch -b ~/bin/terraform'
alias cdg='cd /mnt/c/20-Github'
alias k='kubectl'
alias kpod='kubectl get pods'
alias ksvc='kubectl get svc'
alias klog='kubectl logs'
alias kd='kubectx docker-for-desktop'
alias kci='kubectx arn:aws:eks:us-east-1:054713022081:cluster/ci_stable && export AWS_PROFILE=dev'
alias kdev='kubectx arn:aws:eks:us-east-1:054713022081:cluster/dev_stable && export AWS_PROFILE=dev'
alias kint='kubectx arn:aws:eks:us-east-1:054713022081:cluster/integration_stable && export AWS_PROFILE=dev'
alias kqa='kubectx arn:aws:eks:us-east-1:054713022081:cluster/qa_stable && export AWS_PROFILE=dev'
alias kat='kubectx arn:aws:eks:us-east-1:946092842050:cluster/at_stable && export AWS_PROFILE=at'
alias kstg='kubectx arn:aws:eks:us-east-1:676807884358:cluster/staging_stable && export AWS_PROFILE=staging'
alias kus='kubectx arn:aws:eks:us-east-1:172292293482:cluster/us_stable && export AWS_PROFILE=us'
alias keu='kubectx arn:aws:eks:eu-central-1:172292293482:cluster/eu_stable && export AWS_PROFILE=eu'
alias kap='kubectx arn:aws:eks:ap-northeast-1:172292293482:cluster/apacpr_stable && export AWS_PROFILE=apacpr'
alias kazsbx='kubectx kubernetes && kubens app'
alias kazstg='kubectx azure-staging-kubernetes && kubens app'
alias kazus='kubectx azure-produs-kubernetes && kubens app'
alias k9sat='AWS_PROFILE=at k9s'
alias k9sstg='AWS_PROFILE=staging k9s'
alias k9sus='AWS_PROFILE=us k9s'
alias k9seu='AWS_PROFILE=eu k9s'
alias k9sap='AWS_PROFILE=apacpr k9s'
